"""schema inicial

Revision ID: 863dcb262112
Revises: 
Create Date: 2026-07-16 18:22:52.519814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '863dcb262112'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grupo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('regime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conta_caixa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conta_clientes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conta_fornecedores', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conta_aplicacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conta_saida_sem_match', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('casa_pf', sa.Boolean(), nullable=False),
    sa.Column('tolerancia_valor', sa.Float(), nullable=False),
    sa.Column('janela_dias_despesa', sa.Integer(), nullable=False),
    sa.Column('janela_dias_titulo_pj', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('banco_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conta_banco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_ignorar_despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('termo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_intermediarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_regras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contexto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('modo_match', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conta_debito', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conta_credito', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usa_padrao', sa.Boolean(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao_sem_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao_dinamica', sa.Boolean(), nullable=False),
    sa.Column('confianca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aviso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_terceiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_regra_termos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regra_id', sa.Integer(), nullable=False),
    sa.Column('termo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['regra_id'], ['empresa_regras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa_regra_termos')
    op.drop_table('empresa_terceiros')
    op.drop_table('empresa_regras')
    op.drop_table('empresa_intermediarios')
    op.drop_table('empresa_ignorar_despesa')
    op.drop_table('empresa_bancos')
    op.drop_table('empresas')
    # ### end Alembic commands ###